package com.karis.utamukitchen.di

import com.karis.utamukitchen.models.Food
import com.karis.utamukitchen.utils.Constants
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.components.ApplicationComponent
import javax.inject.Singleton


@InstallIn(ApplicationComponent::class)
@Module
object MenuModule {


    fun provides_menu() : ArrayList<Food>{
        var menu = ArrayList<Food>()

        menu.add(Food(0,"https://cdn.britannica.com/80/157180-050-7B906E02/Heads-wheat-grains.jpg","Wheat", 300, 1,1, Constants.CEREALS,"Wheat is one of the world’s most commonly consumed cereal grains. Whole-grain wheat can be a rich source of various antioxidants, vitamins, minerals, and fiber."))
        menu.add(Food(1,"https://www.world-grain.com/ext/resources/Article-Images/2019/06-June/Corn-flour_AdobeStock_94855632_E.jpg?t=1559745821&width=1080","Maize", 800, 1,1, Constants.CEREALS,"Maize, also known as corn, is a cereal grain first domesticated by indigenous peoples in southern Mexico about 10,000 years ago."))
        menu.add(Food(2,"https://www.world-grain.com/ext/resources/Article-Images/2019/06-June/Corn-flour_AdobeStock_94855632_E.jpg?t=1559745821&width=1080","Rice", 600, 1,1, Constants.CEREALS,"Rice is the seed of the grass species Oryza sativa or less commonly Oryza glaberrima. The name wild rice is usually used for species of the genera Zizania and Porteresia, both wild and domesticated, although the term may also be used for primitive or uncultivated varieties of Oryza"))
        menu.add(Food(3,"https://www.world-grain.com/ext/resources/Article-Images/2018/12---December/Rice_AdobeStock_64819529_E.jpg?1543935249","Rice", 600, 1,1, Constants.CEREALS,"Rice is the seed of the grass species Oryza sativa or less commonly Oryza glaberrima. The name wild rice is usually used for species of the genera Zizania and Porteresia, both wild and domesticated, although the term may also be used for primitive or uncultivated varieties of Oryza"))
        menu.add(Food(4,"https://post.healthline.com/wp-content/uploads/2020/09/barley-benefits-732x549-thumbnail-732x549.jpg","Barley", 500, 1,1, Constants.CEREALS,"Barley is a cereal grain that people can use in bread, beverages, stews, and other dishes. As a whole grain, barley provides fiber, vitamins, and minerals."))
        menu.add(Food(5,"https://i0.wp.com/cdn-prod.medicalnewstoday.com/content/images/articles/311/311409/oatmeal.jpg?w=1155&h=1541","Oat", 450, 1,1, Constants.CEREALS,"Oatmeal is a very popular breakfast food that consists of oats and a liquid, such as water, cow's milk, or plant-based milk. Full of nutrients and fiber, oats are one of the most nutritious whole-grain foods that a person can consume."))
        menu.add(Food(6,"https://www.nationalhogfarmer.com/sites/nationalhogfarmer.com/files/nhf-kws-cereals-usa-llc-hybrid-rye.jpg","Rye", 450, 1,1, Constants.CEREALS,"Rye is a grass grown extensively as a grain, a cover crop and a forage crop. It is a member of the wheat tribe and is closely related to both wheat and barley."))

        menu.add(Food(7,"https://cdn.britannica.com/24/174524-050-A851D3F2/Oranges.jpg","Oranges", 800, 1,1, Constants.FRUITS, "The orange is the fruit of various citrus species in the family Rutaceae; it primarily refers to Citrus × sinensis, which is also called sweet orange, to distinguish it from the related Citrus × aurantium, referred to as bitter orange."))
        menu.add(Food(8,"https://post.healthline.com/wp-content/uploads/2020/09/Do_Apples_Affect_Diabetes_and_Blood_Sugar_Levels-732x549-thumbnail-1-732x549.jpg","Apples", 800, 1,1, Constants.FRUITS, "An apple is an edible fruit produced by an apple tree. Apple trees are cultivated worldwide and are the most widely grown species in the genus Malus. "))
        menu.add(Food(9,"https://post.healthline.com/wp-content/uploads/2020/08/blueberries-732x549-thumbnail.jpg","Berries", 800, 1,1, Constants.FRUITS, "A berry is a small, pulpy, and often edible fruit. Typically, berries are juicy, rounded, brightly colored, sweet, sour or tart, and do not have a stone or pit, although many pips or seeds may be present."))
        menu.add(Food(10,"https://i0.wp.com/cdn-prod.medicalnewstoday.com/content/images/articles/304/304448/limes.jpg?w=1155&h=1541","Limes", 800, 1,1, Constants.FRUITS, "A lime, is a citrus fruit, which is typically round, green in color, 3–6 centimetres in diameter, and contains acidic juice vesicles. There are several species of citrus trees whose fruits are called limes, including the Key lime, Persian lime, kaffir lime, and desert lime."))
        menu.add(Food(11,"https://microbiomepost.com/wp-content/uploads/2019/12/social_preview_16_12_19_pomegranate.jpg","Pomegranate", 800, 1,1, Constants.FRUITS, "The pomegranate is a fruit-bearing deciduous shrub in the family Lythraceae, subfamily Punicoideae, that grows between 5 and 10 m tall."))
        menu.add(Food(12,"https://natashaskitchen.com/wp-content/uploads/2019/06/What-To-Do-With-Lemons-600x900.jpg","Lemon", 800, 1,1, Constants.FRUITS, "The lemon is a species of small evergreen tree in the flowering plant family Rutaceae, native to South Asia, primarily Northeast India. The tree's ellipsoidal yellow fruit is used for culinary and non-culinary purposes throughout the world, primarily for its juice, which has both culinary and cleaning uses."))
        menu.add(Food(13,"https://humboldt.global/wp-content/uploads/2019/07/grapefruitsss.png","Granate", 800, 1,1, Constants.FRUITS, "The grapefruit is a subtropical citrus tree known for its relatively large, sour to semisweet, somewhat bitter fruit. The interior flesh is segmented and varies in color from pale yellow to dark pink."))

        menu.add(Food(14,"https://www.motherjones.com/wp-content/uploads/2020/03/GettyImages-901028510.jpg?w=1200&h=630&crop=1","Beef ", 350, 1,1, Constants.MEAT,"Humans have been eating beef since prehistoric times. Beef is a source of protein and nutrients. Most beef can be used as is by merely cutting into certain parts, such as roasts, short ribs or steak, while other cuts are processed"))
        menu.add(Food(15,"https://i1.wp.com/www.eatthis.com/wp-content/uploads/2020/08/pork-chops.jpg?resize=640%2C360&ssl=1","Pork ", 350, 1,1, Constants.MEAT,"Pork is the culinary name for the meat of a domestic pig. It is the most commonly consumed meat worldwide, with evidence of pig husbandry dating back to 5000 BC. Pork is eaten both freshly cooked and preserved. Curing extends the shelf life of the pork products."))
        menu.add(Food(16,"https://royalmeat.com.bd/wp-content/uploads/2021/03/UTB81r7agn_IXKJkSalUq6yBzVXaa.jpg","Chicken ", 350, 1,1, Constants.MEAT,"Chicken is the most common type of poultry in the world. Owing to the relative ease and low cost of raising them in comparison to animals such as cattle or hogs, chickens have become prevalent in numerous cuisines."))
        menu.add(Food(17,"https://bluehillsfarmshop.co.uk/wp-content/uploads/2017/01/Lamb-Shoulder-400x400.png","Mutton ", 350, 1,1, Constants.MEAT,"Lamb, hogget, and mutton, generically sheep meat, are the meat of domestic sheep, Ovis aries. A sheep in its first year is a lamb and its meat is also lamb. The meat from sheep in their second year are hogget."))
        menu.add(Food(18,"http://d38k7xqy3o8fxn.cloudfront.net/Vault/VaultOutput?ID=8824","Fish ", 350, 1,1, Constants.MEAT,"By some definitions, fish is considered meat, and by others, it isn't. Fish is the flesh of an animal used for food, and by that definition, it's meat. However, many religions don't consider it meat."))

        menu.add(Food(19,"https://news.llu.edu/sites/news.llu.edu/files/styles/featured_image_755x425/public/dairy_milk_copy.jpg?itok=eJ3GQAl6&c=16c81ad48d03de17055901826e1961eb","Milk", 700, 1,1, Constants.MILK,"Milk is a nutrient-rich liquid food produced by the mammary glands of mammals. It is the primary source of nutrition for young mammals, including breastfed human infants before they are able to digest solid food."))
        menu.add(Food(20,"https://uploads-ssl.webflow.com/5e995fb0a6737e51465cdeca/6054367f5f3facb675dc3815_yoghurt-manufacturing-app.jpg","Yogurt", 350, 1,1, Constants.MILK,"Yogurt also spelled yoghurt, yogourt or yoghourt, is a food produced by bacterial fermentation of milk. The bacteria used to make yogurt are known as yogurt cultures."))
        menu.add(Food(21,"https://images-prod.healthline.com/hlcmsresource/images/AN_images/healthiest-cheese-1296x728-swiss.jpg","Cheese", 350, 1,1, Constants.MILK,"Cheese is a dairy product, derived from milk and produced in wide ranges of flavors, textures and forms by coagulation of the milk protein casein. It comprises proteins and fat from milk, usually the milk of cows, buffalo, goats, or sheep. "))
        menu.add(Food(22,"https://cdn.shopify.com/s/files/1/1410/1430/products/a2-desi-cow-ghee-ghee.jpg?v=1605872086","Ghee", 350, 1,1, Constants.MILK,"Ghee is a class of clarified butter that originated in ancient India. It is commonly used in cuisine of the Indian subcontinent, Middle Eastern cuisine, traditional medicine, and religious rituals."))
        menu.add(Food(23,"https://www.news-medical.net/image.axd?picture=2017%2F9%2Fbutter_cubes.jpg","Butter", 350, 1,1, Constants.MILK,"Butter is a dairy product made from the fat and protein components of churned cream. It is a semi-solid emulsion at room temperature, consisting of approximately 80% butterfat."))

        menu.add(Food(24,"https://mk0nutritionadvxtj6i.kinstacdn.com/wp-content/uploads/2019/06/hand-holding-bottle-of-sunflower-oil-with-sunflower-field-in-background.jpg","Sunflower ", 350, 1,1, Constants.OILS,"Sunflower oil is the non-volatile oil pressed from the seeds of sunflower. Sunflower oil is commonly used in food as a frying oil, and in cosmetic formulations as an emollient. Sunflower oil is primarily composed of linoleic acid, a polyunsaturated fat, and oleic acid, a monounsaturated fat."))
        menu.add(Food(25,"https://domf5oio6qrcr.cloudfront.net/medialibrary/2435/w1007d1620724772795.jpg","Palm ", 350, 1,1, Constants.OILS,"Palm oil is an edible vegetable oil derived from the mesocarp of the fruit of the oil palms. The oil is used in food manufacturing, in beauty products, and as biofuel. Palm oil accounted for about 33% of global oils produced from oil crops in 2014."))
        menu.add(Food(26,"https://cdn2.stylecraze.com/wp-content/uploads/2013/11/The-Benefits-And-Bright-Side-Of-Soybean-Oil.jpg","SoyaBean ", 350, 1,1, Constants.OILS,"Soybean oil is a vegetable oil extracted from the seeds of the soybean. It is one of the most widely consumed cooking oils and the second most consumed vegetable oil. As a drying oil, processed soybean oil is also used as a base for printing inks and oil paints."))
        menu.add(Food(27,"https://diana-cdn.naturallycurly.com/Articles/cL_Rapeseed-650x365.jpg","Rape seed ", 350, 1,1, Constants.OILS,"The rapeseed plant usually blooms in the summer and is famous for its golden-yellow flowers. Belonging to the cabbage family, it's closely related to turnip and mustard. Its oil — known both as rapeseed and canola oil — is widely used for cooking, baking, and food processing."))
        menu.add(Food(28,"https://anuna.com/images/detailed/9/79366240.jpg","Mustard ", 350, 1,1, Constants.OILS,"Mustard oil is an essential oil resulting from grinding mustard seed, mixing the grounds with water, and extracting the resulting volatile oil by distillation. Mustard oil is used as cooking oil in some cultures, but sale is restricted in some countries due to high levels of erucic acid."))

        menu.add(Food(29,"https://www.gardeningknowhow.com/wp-content/uploads/2009/03/spinach-400x267.jpg","Spinach ", 350, 1,1, Constants.VEGETABLES,"Spinach is a leafy green flowering plant native to central and western Asia. It is of the order Caryophyllales, family Amaranthaceae, subfamily Chenopodioideae."))
        menu.add(Food(30,"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/cabbage-royalty-free-image-511789974-1546449748.jpg","Cabbage ", 350, 1,1, Constants.VEGETABLES,"Cabbage is a leafy green, red, or white biennial plant grown as an annual vegetable crop for its dense-leaved heads. It is descended from the wild cabbage, and belongs to the \"cole crops\" or brassicas, meaning it is closely related to broccoli and cauliflower; Brussels sprouts; and Savoy cabbage."))
        menu.add(Food(31,"https://cdn.mos.cms.futurecdn.net/r8NK24bmcMgSib5zWKKQkW.jpg","Brocolli ", 350, 1,1, Constants.VEGETABLES,"Broccoli is a good source of fibre and protein, and contains iron, potassium, calcium, selenium and magnesium as well as the vitamins A, C, E, K and a good array of B vitamins including folic acid."))
        menu.add(Food(32,"https://cdn.britannica.com/77/170677-050-F7333D51/lettuce.jpg","Lettuce ", 350, 1,1, Constants.VEGETABLES,"Lettuce is an annual plant of the daisy family, Asteraceae. It is most often grown as a leaf vegetable, but sometimes for its stem and seeds."))
        menu.add(Food(33,"https://images.immediate.co.uk/production/volatile/sites/30/2020/08/health-benefits-of-mushrooms-guide-700-350-349bded.jpg?quality=90&resize=768,574","Mushrooms ", 350, 1,1, Constants.VEGETABLES,"Mushrooms are a rich, low calorie source of fiber, protein, and antioxidants. They may also mitigate the risk of developing serious health conditions, such as Alzheimer's, heart disease, cancer, and diabetes."))
        menu.add(Food(34,"https://www.almanac.com/sites/default/files/image_nodes/beets_by_darasp_kran_ss_crop.jpg","Beets ", 350, 1,1, Constants.VEGETABLES,"The beetroot is the taproot portion of a beet plant, usually known in Canada and the USA as beets while the vegetable is referred to as beetroot in British English, and also known as the table beet, garden beet, red beet, dinner beet or golden beet."))
        menu.add(Food(35,"https://www.almanac.com/sites/default/files/image_nodes/brussels-sprouts.jpg","Brussel ", 350, 1,1, Constants.VEGETABLES,"The City of Brussels is the largest municipality and historical centre of the Brussels-Capital Region, and the capital of Belgium. Besides the strict centre, it also covers the immediate northern outskirts where it borders municipalities in Flanders."))
        menu.add(Food(36,"https://www.healio.com/~/media/slack-news/stock-images/infectious-disease/r/red_onions_adobe_stock.jpeg","Onions ", 350, 1,1, Constants.VEGETABLES,"The onion, also known as the bulb onion or common onion, is a vegetable that is the most widely cultivated species of the genus Allium. The shallot is a botanical variety of the onion. Until 2010, the shallot was classified as a separate species."))
        menu.add(Food(39,"https://ychef.files.bbci.co.uk/976x549/p04w46sp.jpg","Tomatoes ", 350, 1,1, Constants.VEGETABLES,"The tomato is the edible berry of the plant Solanum lycopersicum, commonly known as a tomato plant. The species originated in western South America and Central America. The Nahuatl word tomatl gave rise to the Spanish word tomate, from which the English word tomato derived."))

        return menu
    }

    @Provides
    @Singleton
    fun getsortedData(): ArrayList<Food> {
        return provides_menu()
    }

}